version: "3"

services:

  web:
    build: ./web/
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
#    command: django-admin startproject esnow .
    command: python manage.py runserver 0.0.0.0:8000