version: "3"

services:
  db:
    image: postgres
  web:
    build: ./web/
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
#    command: django-admin startproject esnow .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db